# Generated by Django 5.2.4 on 2025-07-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='name',
            field=models.CharField(default='-', help_text='A unique name for the URL, used for easy identification.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
