# Generated by Django 5.2.4 on 2025-07-27 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted At')),
                ('short_url', models.CharField(help_text='The shortened version of the URL.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the shortened URL is active or not.')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortened_urls', to='shortener.url')),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
            },
        ),
    ]
