# Generated by Django 5.2.4 on 2025-07-27 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_url_name_shorturl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturl',
            options={'verbose_name': 'Short URL', 'verbose_name_plural': 'Short URLs'},
        ),
    ]
