# Generated by Django 5.2.4 on 2025-07-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_shorturl_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the short URL is active or not.'),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(help_text='The short version of the URL.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to='shortener.url'),
        ),
    ]
