# Generated by Django 5.2.4 on 2025-07-29 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('shortener', '0006_url_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlclick',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shorturl'),
        ),
    ]
