# Generated by Django 5.2.4 on 2025-07-29 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_urlclick_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlclick',
            old_name='url',
            new_name='short_url',
        ),
    ]
