name: Deploy URL Shortener (Backend)

on:
  repository_dispatch:
    types: [ trigger-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd url_shortener
            git pull origin master
    
            docker compose -f docker-compose.prod.yml down --volumes=false
            docker compose -f docker-compose.prod.yml up -d --build